name: Pre-Check

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  check-config-files:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Verify critical configuration files are present
      run: |
        test -s autogpts/autogpt/tests/conftest.py
        test -s autogpts/cli.py

  syntax-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Check for syntax errors
      run: python -m compileall autogpts/

  dependency-installation:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Verify dependency installation
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
