name: Python application

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Install dependencies
      run: |
        pip install click PyGithub
        pip install -r requirements.txt
    - name: Run tests
      env:
        CI: true
        GITHUB_ACTIONS: true
      run: pytest
