name: .github/workflows/ci_fix.yml

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install click PyGithub pytest

      - name: Configure Git
        run: |
          git config --global user.name "CI User"
          git config --global user.email "ci@example.com"

      - name: Create dummy .github_access_token
        run: echo "mock_token" > .github_access_token

      - name: Run tests excluding @skip_in_ci
        env:
          CI: true
        run: pytest -v -k "not skip_in_ci"

      - name: Error Handling
        if: ${{ failure() }}
        run: echo "An error occurred during the workflow execution."
