name: Diagnostics Workflow

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  setup-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Configure project environment
        run: |
          echo "Configuring project environment..."
          # Simulate project configuration steps here. Use environment variables and secrets safely.
          echo "Project configured successfully."

      - name: Run tests
        run: pytest autogpts/autogpt/tests/
        env:
          CI: true
        continue-on-error: true

      - name: Capture and display detailed logs on failure
        if: failure()
        run: |
          echo "Tests failed. Displaying logs..."
          # Add commands to display or capture logs here. Ensure sensitive information is not exposed.

      - name: Print environment variables (safely)
        run: |
          printenv | grep -vE '^(AWS|GITHUB)_'
