name: Main CI/CD Pipeline

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Print Environment Variables
      run: |
        printenv | grep -vE '^(_|GITHUB_|AWS_|DOCKER_|NPM_|INPUT_|HOME|PATH|LANG|PWD|SHLVL|GPG_)' || true

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests with CI configuration
      run: pytest --ignore=tests/not_for_ci

    - name: Check for errors
      if: failure()
      run: echo "An error occurred; please check the logs above for more details."

    - name: Notify on Success
      if: success()
      run: echo "Workflow completed successfully, all tests passed."
