name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run tests with pytest
      run: |
        pytest --junitxml=test_results.xml
      continue-on-error: true
    - name: Upload test results
      uses: actions/upload-artifact@v2
      if: always()
      with:
        name: test-results
        path: test_results.xml
    - name: Run other commands
      run: |
        command > command_output.txt 2>&1 || echo "Command failed with exit code $?" > command_error.txt
      continue-on-error: true
    - name: Upload command output
      uses: actions/upload-artifact@v2
      if: always()
      with:
        name: command-output
        path: command_output.txt
    - name: Upload command error log
      uses: actions/upload-artifact@v2
      if: always()
      with:
        name: command-error-log
        path: command_error.txt
