name: .github/workflows/main.yml

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Configure Git
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
    - name: Setup GitHub Access Token
      run: echo "${{ secrets.GITHUB_TOKEN }}" > .github_access_token
    - name: Install dependencies
      run: pip install -r requirements.txt
    - name: Run tests
      run: pytest
