name: CI Workflow

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      env:
        CI: true
        GITHUB_ACTIONS: true
      run: pytest autogpts/autogpt/tests

    - name: Push to repository
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}

    - name: Access private repository
      uses: actions/checkout@v2
      with:
        repository: org/private-repo
        token: ${{ secrets.ACCESS_PRIVATE_REPO_TOKEN }}
        path: private-repo
