name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run tests
      run: pytest
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Capture error logs
      if: failure()
      run: |
        mkdir -p logs
        pytest --last-failed --last-failed-no-failures all > logs/error_logs.txt
    - name: Upload error logs
      uses: actions/upload-artifact@v2
      if: always()
      with:
        name: error-logs
        path: logs/
